#!/usr/bin/ruby

intervals = [
  [32, 64,  128, 192, 256, 512, 544, 1056],
  [32, 64,  128, 192, 256, 512, 544, 1056],
  [32, 256, 1026]
]

counter = -1

intervals[0].size.times do |x1|
  counter += 1
  File.open("flatarray_implementation_#{counter}.cu", "w") do |f|
    f.puts <<EOF
#include <iostream>
#include "cudalineupdatefunctorprototype.h"

EOF

    xA = intervals[0][x1]
    xB = xA

    yA = intervals[1][x1]
    yB = yA

    intervals[2].size.times do |z1|
      zA = intervals[2][z1]
      zB = zA

      f.puts "IMPLEMENTATION(CellLBM, #{xA}, #{yA}, #{zA}, #{xB}, #{yB}, #{zB})"
    end

  end
end
